project:
  type: book

book:
  title: "A Century of Negro Migration"
  author: "Carter Woodson"
  date: "3/31/1918"
  chapters:
    - index.md
    - chapters/00-dedication.md
    - chapters/00-preface.md
    - chapters/chapter-01.md
    - chapters/chapter-02.md
    - chapters/chapter-03.md
    - chapters/chapter-04.md
    - chapters/chapter-05.md
    - chapters/chapter-06.md
    - chapters/chapter-07.md
    - chapters/chapter-08.md
    - chapters/chapter-09.md
    - chapters/chapter-10-bibliography.md
    - progress.md


format:
  html:
    theme:
      - cosmo
      - custom.scss
    number-sections: true

#  pdf:
#    documentclass: scrbook
#    papersize: letter
#    toc: true
#    number-sections: true
#    colorlinks: true



